import assert from "node:assert/strict";
import fs from "node:fs";

const leer = (ruta) => fs.readFileSync(ruta, "utf8");
const mensual = leer("src/components/supervision/DotacionMensualSupervision.jsx");
const componente = leer("src/components/supervision/EstadisticasDotacionSupervision.jsx");
const motor = leer("src/utils/proyeccionSupervisionMes.js");
const reductor = leer("src/utils/estadisticasSupervisionMes.js");
let total = 0;
const probar = (nombre, fn) => { fn(); total += 1; console.log(`OK ${total} ${nombre}`); };

probar("componente estadistico existe", () => assert.equal(fs.existsSync("src/components/supervision/EstadisticasDotacionSupervision.jsx"), true));
probar("importa reductor estadistico", () => assert.match(mensual, /resumirEstadisticasSupervisionMes/));
probar("no importa proyeccion diaria", () => assert.doesNotMatch(componente, /proyectarSupervisionDia/));
probar("no ejecuta segunda proyeccion mensual", () => assert.equal((mensual.match(/proyectarSupervisionMes\(\{/g) || []).length, 1));
probar("resumen recibe resultado mensual", () => assert.match(mensual, /resumirEstadisticasSupervisionMes\(resultadoMensual\)/));
probar("usa useMemo para resumen", () => assert.match(mensual, /const estadisticasMensuales = useMemo/));
probar("selector de turno sigue unico", () => assert.equal((mensual.match(/Turno de la dotaci/g) || []).length, 1));
probar("reutiliza turno seleccionado", () => assert.match(mensual, /turnoSeleccionado=\{turnoSeleccionado\}/));
probar("no usa turnoActivo", () => assert.doesNotMatch(mensual + componente, /turnoActivo/));
probar("selector de categoria existe", () => assert.match(componente, /Categor&iacute;a del resumen mensual/));
probar("Licenciados visible", () => assert.match(mensual, /"Licenciados"/));
probar("Enfermeros visible", () => assert.match(mensual, /"Enfermeros"/));
probar("categoria usa estado local", () => assert.match(componente, /useState\(\(\) => categorias\[0\]\[0\]\)/));
probar("categoria no entra al motor", () => assert.doesNotMatch(mensual.match(/proyectarSupervisionMes\([\s\S]*?\), \[[^\]]+\]\)/)?.[0] || "", /categoriaSeleccionada/));
probar("muestra Dias con datos", () => assert.match(componente, /D&iacute;as con datos/));
probar("usa diasConDatos", () => assert.match(componente, /resumen\.diasConDatos/));
probar("usa diasTotales", () => assert.match(componente, /resumen\.diasTotales/));
probar("muestra dias sin datos", () => assert.match(componente, /resumen\.diasSinDatos/));
probar("muestra Criticos", () => assert.match(componente, /Cr\\u00edticos/));
probar("usa estados criticos", () => assert.match(componente, /resumen\.estados\.criticos/));
probar("muestra Bajo optimo", () => assert.match(componente, /Bajo \\u00f3ptimo/));
probar("usa estados bajoOptimo", () => assert.match(componente, /resumen\.estados\.bajoOptimo/));
probar("muestra Optimos", () => assert.match(componente, /\\u00d3ptimos/));
probar("usa estados optimos", () => assert.match(componente, /resumen\.estados\.optimos/));
probar("no recalcula semaforo", () => assert.doesNotMatch(componente, /estadoDotacion|cantidad\s*[<>]/));
probar("muestra minimo operativo", () => assert.match(componente, /resumen\.minimoOperativo/));
probar("muestra fechas minimo", () => assert.match(componente, /resumen\.fechasMinimoOperativo/));
probar("cero minimo se conserva", () => assert.doesNotMatch(componente, /minimoOperativo\s*\|\|/));
probar("muestra promedio operativo", () => assert.match(componente, /resumen\.promedioOperativo/));
probar("redondea solo en UI", () => assert.match(componente, /maximumFractionDigits: 1/));
probar("no muestra promedio Base", () => assert.doesNotMatch(componente, /promedioBase/));
probar("muestra deficit maximo", () => assert.match(componente, /resumen\.deficitMaximo/));
probar("usa fechas deficit maximo", () => assert.match(componente, /resumen\.fechasDeficitMaximo/));
probar("deficit cero es valido", () => assert.doesNotMatch(componente, /deficitMaximo\s*\|\|/));
probar("muestra advertencias atribuidas", () => assert.match(componente, /resumen\.combinacionesConAdvertencias/));
probar("no inventa warnings globales", () => assert.doesNotMatch(componente, /calidadDatos|advertenciasTotal/));
probar("sin warnings es neutro", () => assert.match(componente, /Sin advertencias atribuidas/));
probar("sin datos evita ceros falsos", () => assert.match(componente, /resumen\.diasConDatos === 0[\s\S]*Sin datos suficientes/));
probar("mes parcial conserva denominador", () => assert.match(componente, /\{resumen\.diasConDatos\} \/ \{resumen\.diasTotales\}/));
probar("incluye nota de datos actuales", () => assert.match(componente, /Calculado con los datos y umbrales actuales/));
probar("no afirma snapshot", () => assert.doesNotMatch(componente, /snapshot|hist.rico congelado/i));
probar("sin cierres", () => assert.doesNotMatch(componente, /cierres|cierreDiario/i));
probar("sin estadisticasCierres", () => assert.doesNotMatch(componente, /estadisticasCierres/));
probar("sin comparacionTurnos", () => assert.doesNotMatch(componente, /comparacionTurnos/));
probar("sin metricas de bajas", () => assert.doesNotMatch(componente, /bajasConocidas|Licencias|Certificaciones/));
probar("sin metricas de Extras", () => assert.doesNotMatch(componente, /extrasRegistrados|extrasQueAportan/));
probar("sin metricas de asistencia", () => assert.doesNotMatch(componente, /asistenciaRegistrada|Presentes|Ausentes/));
probar("sin cobertura sectorial", () => assert.doesNotMatch(componente, /REA|Explora|Sillones|Preinternaci/));
probar("sin Turnantes", () => assert.doesNotMatch(componente, /Turnantes?/));
probar("sin graficos", () => assert.doesNotMatch(componente, /<svg|<canvas|chart/i));
probar("sin nueva libreria", () => assert.doesNotMatch(componente, /recharts|chart\.js|victory/));
probar("read-only", () => assert.doesNotMatch(componente, /<input|<form|contentEditable/));
probar("sin Supabase", () => assert.doesNotMatch(componente, /supabase|rpc\(|\.from\(/i));
probar("sin autosave", () => assert.doesNotMatch(componente, /autosave|guardarEstado/i));
probar("mobile sin width fijo", () => assert.doesNotMatch(componente, /w-\[\d+px\]|min-w-\[\d+px\]/));
probar("sin scroll horizontal", () => assert.doesNotMatch(componente, /overflow-x-auto|whitespace-nowrap/));
probar("buttons tactiles", () => assert.match(componente, /min-h-11/));
probar("aria-pressed", () => assert.match(componente, /aria-pressed=\{activa\}/));
probar("focus visible", () => assert.match(componente, /focus-visible:ring/));
probar("no depende solo de color", () => assert.match(componente, /etiqueta=\{\"Cr\\u00edticos\"\}/));
probar("textos pueden envolver", () => assert.match(componente, /break-words/));
probar("mojibake ausente", () => assert.doesNotMatch(componente, /\u00c3|\u00c2|\u00e2/));
probar("cambio turno alimenta tabla y estadisticas", () => { assert.match(mensual, /dia\.turnos\?\.\[turnoSeleccionado\]/); assert.match(mensual, /turnoSeleccionado=\{turnoSeleccionado\}/); });
probar("cambio categoria no cambia turno", () => assert.doesNotMatch(componente, /setTurnoSeleccionado/));
probar("cambio categoria no recalcula resumen", () => assert.doesNotMatch(componente, /resumirEstadisticasSupervisionMes/));
probar("mismo mensual alimenta tabla y resumen", () => { assert.match(mensual, /resultadoMensual\.dias\.map/); assert.match(mensual, /resumirEstadisticasSupervisionMes\(resultadoMensual\)/); });
probar("motor mensual no modificado conceptualmente", () => assert.match(motor, /proyectarSupervisionDia/));
probar("reductor no modificado conceptualmente", () => assert.match(reductor, /fuente: "proyeccion_supervision_mes"/));
probar("UI no muta input estadistico", () => assert.doesNotMatch(componente, /estadisticas\s*=|\.push\(|\.splice\(/));
probar("Vista sigue read-only", () => assert.doesNotMatch(componente, /guardar|eliminar|actualizarPlanilla|agregarExtra/i));

console.log(`Supervision estadisticas UI: ${total}/${total} comprobaciones OK.`);
