import assert from "node:assert/strict";
import fs from "node:fs";

const leer = (ruta) => fs.readFileSync(ruta, "utf8");
const mensual = leer("src/components/supervision/DotacionMensualSupervision.jsx");
const calidad = leer("src/components/supervision/CalidadDatosSupervision.jsx");
const vista = leer("src/components/supervision/VistaSupervision.jsx");
const novedades = leer("src/components/supervision/NovedadesSupervisionDia.jsx");
const motor = leer("src/utils/proyeccionSupervisionMes.js");
const normalizador = leer("src/utils/alertasSupervisionMes.js");
const estadisticas = leer("src/utils/estadisticasSupervisionMes.js");
let total = 0;
const probar = (nombre, fn) => { fn(); total += 1; console.log(`OK ${total} ${nombre}`); };

probar("componente existe", () => assert.equal(fs.existsSync("src/components/supervision/CalidadDatosSupervision.jsx"), true));
probar("coordinador importa normalizador", () => assert.match(mensual, /construirAlertasSupervisionMes/));
probar("una sola proyeccion mensual", () => assert.equal((mensual.match(/proyectarSupervisionMes\(\{/g) || []).length, 1));
probar("alertas usan resultado mensual", () => assert.match(mensual, /construirAlertasSupervisionMes\(resultadoMensual, erroresCarga\)/));
probar("errores de carga vienen de Vista", () => assert.match(vista, /erroresCarga=\{datos\.errores\}/));
probar("sin nueva consulta Supabase", () => assert.doesNotMatch(calidad + mensual, /supabase|from\(/i));
probar("titulo Calidad de datos", () => assert.match(calidad, /Calidad de datos/));
probar("subtitulo operativo", () => assert.match(calidad, /Situaciones del mes que conviene revisar/));
probar("muestra alertasPresentadas", () => assert.match(calidad, /alertasPresentadas/));
probar("muestra diasAfectados", () => assert.match(calidad, /diasAfectados/));
probar("muestra erroresPresentados", () => assert.match(calidad, /erroresPresentados/));
probar("no muestra conteos crudos", () => assert.doesNotMatch(calidad, /conteosCrudos/));
probar("filtro Todas", () => assert.match(calidad, /\["todas", "Todas"\]/));
probar("filtro Atencion", () => assert.match(calidad, /\["atencion", "Atenci/));
probar("filtro Errores", () => assert.match(calidad, /\["error", "Errores"\]/));
probar("filtro inicial Todas", () => assert.match(calidad, /useState\("todas"\)/));
probar("informacion visible en Todas", () => assert.match(calidad, /filtro === "todas"\s*\? alertas/));
probar("Atencion filtra severidad", () => assert.match(calidad, /alerta\.severidad === filtro/));
probar("Errores filtra severidad", () => assert.match(calidad, /\["error", "Errores"\]/));
probar("filtro no recalcula normalizador", () => assert.doesNotMatch(calidad, /construirAlertasSupervisionMes/));
probar("Calidad no depende de turno", () => assert.doesNotMatch(calidad, /turnoSeleccionado/));
probar("cambio turno no filtra Calidad", () => assert.doesNotMatch(mensual.match(/<CalidadDatosSupervision[\s\S]*?\/>/)?.[0] || "", /turnoSeleccionado/));
probar("lista usa resultado alertas", () => assert.match(calidad, /resultado\?\.alertas/));
probar("no reordena alertas", () => assert.doesNotMatch(calidad, /\.sort\(/));
probar("titulo humano visible", () => assert.match(calidad, /alerta\.titulo/));
probar("codigo no es titulo", () => assert.doesNotMatch(calidad, /<h4[^>]*>\{alerta\.codigo\}/));
probar("fecha breve", () => assert.match(calidad, /partes\[2\].*partes\[1\]/));
probar("sin fecha tiene contexto", () => assert.match(calidad, /Mes completo.*General/));
probar("turno usa TURNOS", () => assert.match(calidad, /TURNOS\[alerta\.turno\]\.nombre/));
probar("categoria humana", () => assert.match(calidad, /CATEGORIAS\[alerta\.categoria\]/));
probar("personaId no se presenta", () => assert.doesNotMatch(calidad, /alerta\.personaId/));
probar("turno origen en detalle", () => assert.match(calidad, /<strong>Origen:<\/strong>/));
probar("error tiene texto", () => assert.match(calidad, /error: \{ etiqueta: "Error"/));
probar("atencion tiene texto", () => assert.match(calidad, /atencion: \{ etiqueta: "Atenci/));
probar("informacion tiene texto", () => assert.match(calidad, /informacion: \{ etiqueta: "Informaci/));
probar("no depende solo del color", () => assert.match(calidad, /severidad\.etiqueta/));
probar("detalle expandible", () => assert.match(calidad, /Ver detalle.*Ocultar detalle|Ocultar detalle.*Ver detalle/));
probar("aria-expanded", () => assert.match(calidad, /aria-expanded=\{abierta\}/));
probar("aria-controls", () => assert.match(calidad, /aria-controls=\{detalleId\}/));
probar("una alerta abierta", () => assert.match(calidad, /actual === alerta\.id \? null : alerta\.id/));
probar("detalle humano", () => assert.match(calidad, /alerta\.detalle/));
probar("accion interna traducida", () => assert.match(calidad, /ACCIONES\[alerta\.accion\]/));
probar("accion cruda no se renderiza", () => assert.doesNotMatch(calidad, />\{alerta\.accion\}</));
probar("codigo solo en detalle", () => assert.match(calidad, /Código técnico:<\/strong> \{alerta\.codigo\}/));
probar("codigo null se omite", () => assert.match(calidad, /alerta\.codigo != null/));
probar("motivo no es titulo", () => assert.doesNotMatch(calidad, /<h4[^>]*>\{alerta\.motivo\}/));
probar("cantidad como registros", () => assert.match(calidad, /Registros involucrados/));
probar("periodo se conserva", () => assert.match(calidad, /alerta\.clavePeriodo/));
probar("limite inicial cinco", () => assert.match(calidad, /LIMITE_INICIAL = 5/));
probar("Ver todas", () => assert.match(calidad, /Ver todas/));
probar("Ver menos", () => assert.match(calidad, /Ver menos/));
probar("filtro vuelve a compacto", () => assert.match(calidad, /setMostrarTodas\(false\)/));
probar("sin alertas mensaje especifico", () => assert.match(calidad, /No hay alertas de calidad para este mes/));
probar("filtro vacio distinto", () => assert.match(calidad, /No hay alertas en este filtro/));
probar("carga estados global catalogada", () => assert.match(normalizador, /No se pudieron cargar los estados mensuales/));
probar("carga estados sin turno inventado", () => assert.match(normalizador, /\["carga_estados", erroresCarga\?\.estados\]/));
probar("carga estados sin categoria inventada", () => assert.doesNotMatch(calidad, /erroresCarga\.estados/));
probar("carga novedades global catalogada", () => assert.match(normalizador, /No se pudieron cargar todas las Novedades/));
probar("Planilla no se multiplica en UI", () => assert.doesNotMatch(calidad, /PLANILLA_NO_PREPARADA/));
probar("periodos separados quedan separados", () => assert.match(calidad, /visibles\.map\(\(alerta\)/));
probar("UI no deduplica", () => assert.doesNotMatch(calidad, /new Set|Map\(/));
probar("conserva orden del contrato", () => assert.match(calidad, /filtradas\.slice\(0, LIMITE_INICIAL\)/));
probar("nota datos actuales", () => assert.match(calidad, /Basado en los datos actuales del mes/));
probar("no mezcla Novedades validas", () => assert.doesNotMatch(calidad, /CERTIFICACION_DIA|adhesion_paro|cambio_horario|olvido_tarjeta/));
probar("no mezcla cobertura", () => assert.doesNotMatch(calidad, /REA|Explora|Sillones|Preinternaci.n/));
probar("read-only", () => assert.doesNotMatch(calidad, /onSubmit|<form|<input/));
probar("sin guardar", () => assert.doesNotMatch(calidad, /guardar/i));
probar("sin editar", () => assert.doesNotMatch(calidad, /editar/i));
probar("sin borrar", () => assert.doesNotMatch(calidad, /borrar|eliminar/i));
probar("sin autosave", () => assert.doesNotMatch(calidad, /autosave/i));
probar("sin graficos", () => assert.doesNotMatch(calidad, /canvas|svg|chart/i));
probar("mobile sin width rigido", () => assert.doesNotMatch(calidad, /w-\[(?:[4-9]\d\d|\d{4,})px\]/));
probar("sin scroll horizontal", () => assert.doesNotMatch(calidad, /overflow-x-(?:auto|scroll)/));
probar("filtros tactiles", () => assert.match(calidad, /min-h-11/));
probar("focus visible", () => assert.match(calidad, /focus-visible:ring/));
probar("texto puede envolver", () => assert.match(calidad, /break-words/));
probar("loading evita datos viejos", () => assert.ok(mensual.indexOf("if (cargando)") < mensual.indexOf("<CalidadDatosSupervision")));
probar("cambio mes actualiza alertas", () => assert.match(mensual, /\[resultadoMensual, erroresCarga\]/));
probar("detalle viejo se cierra por key de mes", () => assert.match(mensual, /key=\{alertasMensuales\.mes\}/));
probar("motor mensual no modificado por UI", () => assert.doesNotMatch(motor, /CalidadDatosSupervision|construirAlertasSupervisionMes/));
probar("normalizador no importa UI", () => assert.doesNotMatch(normalizador, /CalidadDatosSupervision|react/i));
probar("reductor no importa UI", () => assert.doesNotMatch(estadisticas, /CalidadDatosSupervision|react/i));
probar("no resuelve personas", () => assert.doesNotMatch(calidad, /personaId|personaNombre|Personal/));
probar("no procesa Planilla", () => assert.doesNotMatch(calidad, /estadosPorTurno|datosPlanilla|procesarPlanilla/));
probar("mojibake ausente", () => assert.doesNotMatch(calidad + mensual + vista + novedades, /\u00c3|\u00c2|\u00e2/));
probar("Todas muestra cantidad", () => assert.match(calidad, /\{etiqueta\} <span[^>]*>\{cantidadesFiltro\[valor\]\}/));
probar("Atencion deriva cantidad de alertas", () => assert.match(calidad, /atencion: alertas\.filter\(\(alerta\) => alerta\.severidad === "atencion"\)\.length/));
probar("Errores deriva cantidad de alertas", () => assert.match(calidad, /error: alertas\.filter\(\(alerta\) => alerta\.severidad === "error"\)\.length/));
probar("Todas deriva de alertas length", () => assert.match(calidad, /todas: alertas\.length/));
probar("acentos renderizables son UTF8 real", () => {
  assert.match(calidad, /Días afectados/);
  assert.match(calidad, /Acción sugerida/);
  assert.match(calidad, /Código técnico/);
  assert.doesNotMatch(calidad, /\\u00[0-9a-f]{2}/i);
});
probar("Novedades inicia compacta", () => assert.match(novedades, /useState\(false\)/));
probar("resumen Novedades siempre visible", () => assert.match(novedades, /Total \{resumen\.total\}[\s\S]*Ausencias \{resumen\.ausencias\}[\s\S]*Informativas \{resumen\.informativas\}/));
probar("botones Novedades", () => assert.match(novedades, /Ocultar novedades.*Ver novedades|Ver novedades.*Ocultar novedades/));
probar("accesibilidad Novedades", () => {
  assert.match(novedades, /aria-expanded=\{expandido\}/);
  assert.match(novedades, /aria-controls="contenido-novedades-supervision-dia"/);
});
probar("expandir conserva lista", () => assert.match(novedades, /expandido &&[\s\S]*novedades\.map/));
probar("cambio fecha reinicia Novedades", () => assert.match(vista, /<NovedadesSupervisionDia[\s\S]*key=\{fecha\}/));
probar("Calidad antes de filas", () => assert.ok(mensual.indexOf("<CalidadDatosSupervision") < mensual.indexOf("resultadoMensual.dias.map")));
probar("Calidad despues del resumen", () => assert.ok(mensual.indexOf("<EstadisticasDotacionSupervision") < mensual.indexOf("<CalidadDatosSupervision")));
probar("normalizador permanece aislado", () => assert.doesNotMatch(normalizador, /CalidadDatosSupervision|NovedadesSupervisionDia/));

assert.equal(total, 99);
console.log(`Supervisi\u00f3n Calidad de datos: ${total}/${total} pruebas OK`);
