import assert from "node:assert/strict";
import fs from "node:fs";

const leer = (ruta) => fs.readFileSync(ruta, "utf8");
const vista = leer("src/components/supervision/VistaSupervision.jsx");
const detalle = leer("src/components/supervision/DetalleCategoriaSupervision.jsx");
const conjunto = `${vista}\n${detalle}`;
let total = 0;
const probar = (nombre, prueba) => { prueba(); total += 1; console.log(`OK ${total} ${nombre}`); };

probar("existe Ver detalle",()=>assert.match(vista,/Ver detalle/));
probar("detalle usa button real",()=>assert.match(vista,/<button[\s\S]*Ver detalle/));
probar("expone aria-expanded",()=>assert.match(vista,/aria-expanded=\{abierto\}/));
probar("expone aria-controls",()=>assert.match(vista,/aria-controls=\{detalleId\}/));
probar("detalle es read only",()=>assert.doesNotMatch(detalle,/<input|<select|<textarea/));
probar("muestra previstos base",()=>assert.match(detalle,/proyeccion\.previstosBase/));
probar("muestra bajas conocidas",()=>assert.match(detalle,/proyeccion\.bajasConocidas/));
probar("muestra base disponible",()=>assert.match(detalle,/proyeccion\.baseDisponible/));
probar("muestra Extras registrados",()=>assert.match(detalle,/proyeccion\.extrasRegistrados/));
probar("muestra Extras que aportan",()=>assert.match(detalle,/proyeccion\.extrasQueAportan/));
probar("muestra dotacion operativa",()=>assert.match(detalle,/proyeccion\.dotacionPrevistaOperativa/));
probar("muestra libres programados",()=>assert.match(detalle,/proyeccion\.libresProgramados/));
probar("libres son fila separada de bajas",()=>assert.match(detalle,/Libres programados[\s\S]*Bajas conocidas/));
probar("lista personas de baja",()=>assert.match(detalle,/bajasConocidas\?\.personas/));
probar("presenta Licencia",()=>assert.match(detalle,/licencia: "Licencia"/));
probar("presenta Certificacion",()=>assert.match(detalle,/certificacion: "Certificaci/));
probar("presenta Suspension",()=>assert.match(detalle,/suspension: "Suspensi/));
probar("presenta Adhesion a paro",()=>assert.match(detalle,/adhesion_paro: "Adhesi/));
probar("presenta No disponible",()=>assert.match(detalle,/no_disponible: "No disponible"/));
probar("conserva causas multiples",()=>assert.match(detalle,/persona\.causas\.map[\s\S]*\.join\(" · "\)/));
probar("sin bajas tiene mensaje",()=>assert.match(detalle,/Sin bajas conocidas/));
probar("conteo registrados viene del motor",()=>assert.match(detalle,/metrica=\{proyeccion\.extrasRegistrados\}/));
probar("conteo aportes viene del motor",()=>assert.match(detalle,/metrica=\{proyeccion\.extrasQueAportan\}/));
probar("lista Extras que aportan",()=>assert.match(detalle,/extrasQueAportan\?\.personas/));
probar("no reconstruye motor Extras",()=>assert.doesNotMatch(detalle,/obtenerClaveIdentidadPersona|resolverPersona|filter\(/));
probar("muestra asistencia registrada",()=>assert.match(detalle,/Asistencia registrada/));
probar("muestra presentes",()=>assert.match(detalle,/asistencia\.presentes/));
probar("muestra ausentes",()=>assert.match(detalle,/asistencia\.ausentes/));
probar("muestra pendientes",()=>assert.match(detalle,/asistencia\.pendientes/));
probar("asistencia null muestra sin datos",()=>assert.match(detalle,/asistencia == null[\s\S]*Asistencia sin datos/));
probar("asistencia no cambia dotacion",()=>assert.doesNotMatch(detalle,/dotacionPrevistaOperativa\s*[=+-]/));
probar("lista ausentes registrados",()=>assert.match(detalle,/asistencia\.ausentes\.personas/));
probar("no usa presenciaReal",()=>assert.doesNotMatch(conjunto,/presenciaReal|presencia real/i));
probar("sin datos evita metricas falsas",()=>assert.match(detalle,/!disponible \|\| !proyeccion/));
probar("cero real se muestra por cantidad",()=>assert.match(detalle,/\{metrica\?\.cantidad\}/));
probar("keys priorizan identidad estable",()=>assert.match(detalle,/persona\?\.personaId \|\| persona\?\.id \|\| persona\?\.funcionario/));
probar("cambio de fecha cierra detalle",()=>assert.match(vista,/const cambiarFecha[\s\S]*setDetalleAbierto\(null\)/));
probar("loading conjunto oculta el tablero con detalle",()=>assert.match(vista,/cargandoPanel \?[\s\S]*TarjetaTurno/));
probar("no consulta Supabase",()=>assert.doesNotMatch(conjunto,/supabase/i));
probar("no guarda datos",()=>assert.doesNotMatch(conjunto,/guardarEstado|actualizarEstado|insert\(|upsert\(/));
probar("mobile no usa widths fijos",()=>assert.doesNotMatch(detalle,/w-\[(?:\d+)px\]/));

console.log(`Supervision detalle: ${total}/${total} comprobaciones OK.`);
