import assert from "node:assert/strict";
import fs from "node:fs";

const ruta = "supabase/migrations/20260820_crear_configuracion_dotacion_supervision_mes.sql";
const sql = fs.readFileSync(ruta, "utf8");
const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
let total = 0;
const probar = (nombre, prueba) => { prueba(); total += 1; console.log(`OK ${nombre}`); };

probar("1 tabla principal", () => assert.match(sql, /create table if not exists public\.configuracion_dotacion_supervision_mes/));
probar("2 PK mes", () => assert.match(sql, /mes text primary key/));
probar("3 mes valido", () => assert.match(sql, /\^\[0-9\]\{4\}-\(0\[1-9\]\|1\[0-2\]\)\$/));
probar("4 configuracion objeto", () => assert.match(sql, /jsonb_typeof\(p_configuracion\) <> 'object'/));
probar("5 defaults obligatorios", () => assert.match(sql, /not \(p_configuracion \? 'defaults'\)/));
probar("6 LE minimo", () => assert.match(sql, /array\['licenciado', 'enfermero'\]/));
probar("7 LE optimo", () => assert.match(sql, /v_umbral \? 'optimo'/));
probar("8 AE minimo", () => assert.match(sql, /'enfermero'/));
probar("9 AE optimo", () => assert.match(sql, /jsonb_typeof\(v_umbral -> 'optimo'\) <> 'number'/));
probar("10 optimo mayor minimo", () => assert.match(sql, /'optimo'\)::numeric < \(v_umbral ->> 'minimo'\)::numeric/));
probar("11 turnos validos", () => assert.match(sql, /'noche', 'manana', 'tarde', 'vespertino'/));
probar("12 categorias validas", () => assert.match(sql, /v_categoria not in \('licenciado', 'enfermero'\)/));
probar("13 overrides parciales", () => assert.match(sql, /if p_configuracion \? 'overridesTurno'/));
probar("14 sin claves arbitrarias", () => assert.match(sql, /where clave not in \('defaults', 'overridesTurno'\)/));
probar("15 revision inicial", () => assert.match(sql, /revision bigint not null default 1/));
probar("16 revision backend", () => assert.match(sql, /revision = revision \+ 1/));
probar("17 creacion segura", () => assert.match(sql, /p_revision_esperada = 0[\s\S]*on conflict \(mes\) do nothing/));
probar("18 conflicto revision", () => assert.match(sql, /'codigo', 'REVISION_CONFLICTO'/));
probar("19 actor auth uid", () => assert.match(sql, /v_actor uuid := \(select auth\.uid\(\)\)/));
probar("20 solo supervision guarda", () => assert.match(sql, /not \(select private\.usuario_app_es_supervision\(\)\)/));
probar("21 insert directo bloqueado", () => assert.match(sql, /revoke all privileges on table public\.configuracion_dotacion_supervision_mes[\s\S]*from public, anon, authenticated/));
probar("22 update directo bloqueado", () => assert.doesNotMatch(sql, /grant (?:insert|update)/));
probar("23 delete directo bloqueado", () => assert.doesNotMatch(sql, /grant delete/));
probar("24 select supervision", () => assert.match(sql, /supervision_select_configuracion_dotacion_supervision_mes[\s\S]*private\.usuario_app_es_supervision/));
probar("25 historico rechazado", () => assert.match(sql, /p_mes < v_mes_actual[\s\S]*MES_HISTORICO_PROTEGIDO/));
probar("26 mes actual permitido", () => assert.doesNotMatch(sql, /p_mes <= v_mes_actual/));
probar("27 mes futuro permitido", () => assert.doesNotMatch(sql, /p_mes > v_mes_actual[\s\S]*raise exception/));
probar("28 zona Montevideo", () => assert.match(sql, /America\/Montevideo/));
probar("29 historial existe", () => assert.match(sql, /create table if not exists public\.historial_configuracion_dotacion_supervision_mes/));
probar("30 historial PK", () => assert.match(sql, /primary key \(mes, revision\)/));
probar("31 revision uno historial", () => assert.match(sql, /after insert or update/));
probar("32 updates historial", () => assert.match(sql, /actualizacion_cas/));
probar("33 snapshot completo", () => assert.match(sql, /new\.configuracion/));
probar("34 changed by backend", () => assert.match(sql, /new\.updated_by/));
probar("35 historial no editable", () => assert.doesNotMatch(sql, /grant update on table public\.historial/));
probar("36 historial no eliminable", () => assert.doesNotMatch(sql, /grant delete on table public\.historial/));
probar("37 transaccion atomica", () => assert.match(sql, /^begin;[\s\S]*commit;\s*$/));
probar("38 invalido no revisa", () => assert.ok(sql.indexOf("CONFIGURACION_INVALIDA") < sql.indexOf("revision = revision + 1")));
probar("39 historico no revisa", () => assert.ok(sql.indexOf("MES_HISTORICO_PROTEGIDO") < sql.indexOf("revision = revision + 1")));
probar("40 historico no historial", () => assert.ok(sql.indexOf("MES_HISTORICO_PROTEGIDO") < sql.indexOf("insert into public.configuracion_dotacion_supervision_mes")));
probar("41 security definer", () => assert.match(sql, /guardar_configuracion_dotacion_supervision_mes[\s\S]*security definer/));
probar("42 search path seguro", () => assert.match(sql, /security definer\s+set search_path = ''/));
probar("43 no frontend", () => assert.doesNotMatch(sql, /useConfiguracionDotacionSupervision|React|src\/hooks/));
probar("44 no motor", () => assert.doesNotMatch(sql, /proyectarSupervision|resolverEstadoDotacion/));
probar("45 defaults no modificados", () => {
  const motor = fs.readFileSync("src/utils/dotacionSupervision.js", "utf8");
  assert.match(motor, /licenciado: Object\.freeze\(\{ minimo: 9, optimo: 11 \}\)/);
  assert.match(motor, /enfermero: Object\.freeze\(\{ minimo: 13, optimo: 16 \}\)/);
});
probar("script registrado", () => assert.equal(packageJson.scripts["test:umbrales-supervision-sql"], "node tests/umbrales-supervision-sql.test.mjs"));

assert.equal(total, 46);
console.log(`Umbrales Supervisión SQL: ${total}/${total} comprobaciones OK.`);
